# Werkcollege-opdrachten Week 1.3

## Dependencies importeren

Kopieer in het codeblok hieronder van het vorige practicum de import-code voor de dependencies die het vaakst worden gebruikt om data in te lezen. Geef er ook de gebruikelijke aliassen aan.<br>
Zet eventuele warnings uit.

In [110]:
import pandas as pd
import warnings
warnings.simplefilter('ignore')

Zet het bestand go_sales_train.sqlite in een makkelijk te vinden map

## Databasetabellen inlezen

Kopieer in het codeblok hieronder van het vorige practicum de code om een connectie met het bestand go_sales_train.sqlite te maken.

In [111]:
import sqlite3
try:
    sqliteConnection = sqlite3.connect('go_sales_train.sqlite')
    cursor = sqliteConnection.cursor()
    print('Db created and connected succesfull')
except sqlite3.Error as error:
    print('Error occured: ', error)

Db created and connected succesfull

Lees van de ingelezen go_sales_train-database te volgende tabellen in met behulp van "SELECT * FROM *tabel*".
- product
- product_type
- product_line
- sales_staff
- sales_branch
- retailer_site
- country
- order_header
- order_details
- returned_item
- return_reason

In [112]:
sales = cursor.execute("SELECT * FROM product")
result = cursor.fetchall()
result

[(1,
  '1995-02-15',
  1,
  4.0,
  0.33,
  'P01CE1CG1.jpg',
  'EN',
  'TrailChef Water Bag',
  'Lightweight, collapsible bag to carry liquids easily.  Wide mouth for easy filling.  Holds 10 liters.'),
 (2,
  '1995-02-15',
  1,
  9.22,
  0.23,
  'P02CE1CG1.jpg',
  'EN',
  'TrailChef Canteen',
  'Aluminum canteen. Rugged fleece-lined cover with belt clips, removable shoulder sling and small pocket for water purification tablets bottle. Holds 2 liters'),
 (3,
  '1995-02-15',
  1,
  15.93,
  0.28,
  'P03CE1CG1.jpg',
  'EN',
  'TrailChef Kitchen Kit',
  'Zippered nylon pouch contains cutlery for two, can opener, wire whisk, scrubber sponge, 2  60 ml squirt bottles, pancake turner and salt and pepper shaker.  Measures 10 x 22 x 5 cm.'),
 (4,
  '1995-02-15',
  1,
  5.0,
  0.28,
  'P04CE1CG1.jpg',
  'EN',
  'TrailChef Cup',
  'Tin cup. Holds 0.4 liters. Weight: 60 g'),
 (5,
  '1995-02-15',
  1,
  34.97,
  0.3,
  'P05CE1CG1.jpg',
  'EN',
  'TrailChef Cook Set',
  'All you will ever need on the trail.  Pot gripper and nylon carrying bag included.  1.5 and 2 liter pots with individual lids. Weight: 750 g.'),
 (6,
  '1997-03-05',
  1,
  85.11,
  0.28,
  'P06CE1CG1.jpg',
  'EN',
  'TrailChef Deluxe Cook Set',
  'Cascade set features 1, 2, and 3 liter pots with individual lids that double as fry pans or plates. Pot gripper and nylon carrying bag included.  Weight: 1.4 kg.'),
 (7,
  '1995-02-15',
  1,
  46.38,
  0.28,
  'P07CE1CG1.jpg',
  'EN',
  'TrailChef Single Flame',
  'A single burner stove with integral tank.  It features precise flame control so you will never have to settle for burnt camp food again.  Weight 624 g, fuel is white gas.'),
 (8,
  '1997-03-05',
  1,
  75.0,
  0.41,
  'P08CE1CG1.jpg',
  'EN',
  'TrailChef Double Flame',
  'The TrailChef Double Flame is a camp stove which attaches directly to fuel canisters. Features precise flame control and a built-in windscreen.  Weight is 850 g, fuel is propane.'),
 (9,
  '1997-03-05',
  1,
  9.0,
  0.25,
  'P09CE1CG1.jpg',
  'EN',
  'TrailChef Kettle',
  'This old-fashioned style kettle is made of durable enamel.  Weight: 350g, Holds 1.5 liters.'),
 (10,
  '1995-02-15',
  1,
  10.0,
  0.4,
  'P10CE1CG1.jpg',
  'EN',
  'TrailChef Utensils',
  'Spoon, fork and knife set made of a light yet strong metal alloy.  Carrying pouch included.'),
 (11,
  '1995-02-15',
  2,
  250.0,
  0.28,
  'P11CE1TN2.jpg',
  'EN',
  'Star Lite',
  'A perfect tent for biking and hiking trips, compact and very light.  Features three shock cord aluminum poles, and three large mesh windows.  Packed size: 15 x 40 cm. Weight: 0.5 kg.'),
 (12,
  '1997-03-05',
  2,
  473.07,
  0.23,
  'P12CE1TN2.jpg',
  'EN',
  'Star Dome',
  'Four pole geodesic dome mountain tent that comfortably fits two to three people. 10 mm aluminum poles, mesh pole sleeves and taped seams.  Packed size: 22 x 63 cm. Weight: 4.8 kg.'),
 (13,
  '1995-02-15',
  2,
  392.57,
  0.25,
  'P13CE1TN2.jpg',
  'EN',
  'Star Gazer 2',
  "The Star Gazer 2 is the Great Outdoor's most versatile tent.  It is a large two-person tent that is both durable and light weight.  Packed size: 18 x 70 cm. Weight: 2.6 kg."),
 (14,
  '1997-03-05',
  2,
  476.0,
  0.2,
  'P14CE1TN2.jpg',
  'EN',
  'Star Gazer 3',
  'The Star Gazer 3 features a water proof fly, mesh window and two doors for good ventilation.  Packed size: 20 x 70 cm. Weight: 5.3 kg.'),
 (15,
  '1997-03-05',
  2,
  490.0,
  0.33,
  'P15CE1TN2.jpg',
  'EN',
  'Star Gazer 6',
  'Massive cabin tent has ample room for six people. Mesh door and vent, T-style door.  Four side windows with storm flaps and three carry bags for tent and poles.'),
 (16,
  '1997-03-05',
  2,
  1.0,
  0.5,
  'P16CE1TN2.jpg',
  'EN',
  'Star Peg',
  'A single tent peg made of heavy-duty plated steel. Long enough even for hard, rocky ground. Length: 25 cm'),
 (17,
  '1997-03-05',
  3,
  60.0,
  0.28,
  'P17CE1SB3.jpg',
  'EN',
  'Hibernator Lite',
  'The Hibernator Lite is the perfect summer sleeping bag.  Light weight and comfortable down to 10¦C.  The rectangular shape allows for easy pairing.  Weight with stuff sack: 1.0 kg.'),
 (18,
  '1995-02-15',
  3,
  86.0,
  0.33,
  'P17CE1SB3.jpg',
  'EN',
  'Hibernator',
  'The Hibernator is a three-season sleeping bag. The rectangular shape allows for easy pairing. Nylon shell material.  8 cm loft.  Comfortable down to 0¦C.  One size fits up to 195 cm.'),
 (19,
  '2000-10-26',
  3,
  150.0,
  0.37,
  'P19CE1SB3.jpg',
  'EN',
  'Hibernator Extreme',
  'The Hibernator Extreme has all the features you need for four-season comfort.  Comfortable from -18¦ to 9¦C. Silk comfort lining, nylon shell. Fits users to 195 cm, stuff sack included.'),
 (20,
  '1997-03-05',
  3,
  78.55,
  0.28,
  'P20CE1SB3.jpg',
  'EN',
  'Hibernator Self - Inflating Mat',
  'Mattress is made of extra-thick foam. Mesh stuff sack included for easy carrying and storage. Repair kit included.'),
 (21,
  '1995-02-15',
  3,
  29.17,
  0.17,
  'P21CE1SB3.jpg',
  'EN',
  'Hibernator Pad',
  'Warms up quickly for snow camping comfort. The Hibernator Pad will resist cracking in temperatures as low as -30¦C.'),
 (22,
  '1995-02-15',
  3,
  10.0,
  0.33,
  'P22CE1SB3.jpg',
  'EN',
  'Hibernator Pillow',
  'Camp pillow is filled with soft, luxurious fibers for maximum compactness and resiliency. Covered with soft cotton on one side and soft flannel on the other.'),
 (23,
  '1997-03-05',
  3,
  65.33,
  0.33,
  'P23CE1SB3.jpg',
  'EN',
  'Hibernator Camp Cot',
  'Aluminum frame camp cot that is lightweight and durable.  Size: 100 x 225 x 50 cm.  Weight: 7 kg.'),
 (24,
  '1997-03-05',
  4,
  62.5,
  0.17,
  'P24CE1PK4.jpg',
  'EN',
  'Canyon Mule Climber Backpack',
  'This pack is perfect for day trips and short hikes. Also great for students.  Separate front compartment, multi-layered interior organizer, 2 cm waist belt, 32,000 cu. cm.'),
 (25,
  '1995-02-15',
  4,
  166.66,
  0.33,
  'P25CE1PK4.jpg',
  'EN',
  'Canyon Mule Weekender Backpack',
  'A weekend getaway requires this pack.  It features a large front compression pocket, harness and waist belt, foam molded back panel, vinyl covered gear loops.  50,000 cu. cm.'),
 (26,
  '1995-02-15',
  4,
  213.33,
  0.33,
  'P26CE1PK4.jpg',
  'EN',
  'Canyon Mule Journey Backpack',
  'Set of three packs: handlebar pack, front pack and rear pack.  Designed to fit most mountain bikes.  Includes mounting hardware.  Total volume: 66,000 cu. cm.'),
 (27,
  '1997-03-05',
  4,
  238.88,
  0.43,
  'P27CE1PK4.jpg',
  'EN',
  'Canyon Mule Extreme Backpack',
  'Perfect for long back country trips, this pack features an expandable front pocket, includes a large sleeping bag compartment, padded shoulder harness, back and waist belt. 90,000 cu. cm.'),
 (28,
  '1995-02-15',
  4,
  24.0,
  0.2,
  'P28CE1PK4.jpg',
  'EN',
  'Canyon Mule Cooler',
  'A durable plastic cooler with hinged top, perfect for storing small items. Size:100 x 50 x 50 cm.'),
 (29,
  '1997-03-05',
  4,
  41.18,
  0.4,
  'P29CE1PK4.jpg',
  'EN',
  'Canyon Mule Carryall',
  'This pack has a large capacity, perfect for carrying all your camping gear.  Solid metal zipper and leather bottom.'),
 (30,
  '1997-03-05',
  5,
  6.75,
  0.5,
  'P30CE1LT5.jpg',
  'EN',
  'Firefly Lite',
  'Lightweight flashlight made from aircraft aluminum. Focusable beam, tail cap push button allows for single-handed operation. Uses two AA batteries, included.'),
 (31,
  '1997-03-05',
  5,
  7.5,
  0.5,
  'P31CE1LT5.jpg',
  'EN',
  'Firefly Mapreader',
  'Clip-on flashlight for map or book reading. Also comes with flexible fiber optic extension. Lightweight, uses only one AA battery, included.'),
 (32,
  '1995-02-15',
  5,
  16.67,
  0.33,
  'P32CE1LT5.jpg',
  'EN',
  'Firefly 2',
  'A high quality aluminum flashlight with Krypton bulb.  Uses two D batteries, included.'),
 (33,
  '1997-03-05',
  5,
  18.0,
  0.33,
  'P33CE1LT5.jpg',
  'EN',
  'Firefly 4',
  'Made of solid plastic construction, adjustable beam (flood to spot), Krypton bulb.  Uses four D batteries, included.'),
 (34,
  '2000-10-26',
  5,
  28.12,
  0.37,
  'P34CE1LT5.jpg',
  'EN',
  'Firefly Extreme',
  'The Firefly Extreme is under 15 cm long yet produces 7,000 candlepower using two lithium batteries and a Xenon bulb. Shock and water resistant. Weight: 135 g.'),
 (35,
  '2000-10-26',
  5,
  17.78,
  0.25,
  'P35CE1LT5.jpg',
  'EN',
  'Firefly Multi-light',
  'This light can be used as either a flashlight or as a lamp. Uses two C batteries, included.  Burn time 7-8 hours. Water-resistant.'),
 (36,
  '1995-02-15',
  5,
  18.05,
  0.4,
  'P36CE1LT5.jpg',
  'EN',
  'EverGlow Single',
  'Light output approximates a 100 W bulb. Single mantle regulated. Porcelain dome. Uses 0.5 liter  propane cylinder (not included).'),
 (37,
  '1997-03-05',
  5,
  28.75,
  0.37,
  'P37CE1LT5.jpg',
  'EN',
  'EverGlow Double',
  'Light output approximates a 175 W bulb. Double mantle regulated. Porcelain dome. Uses 0.5 liter propane cylinder (not included).'),
 (38,
  '1997-03-05',
  5,
  20.0,
  0.33,
  'P38CE1LT5.jpg',
  'EN',
  'EverGlow Kerosene',
  "One of the most dependable sources of light in an emergency, this lantern is always ready and doesn't need to be recharged. Cotton wick. Height: 30 cm."),
 (39,
  '1997-03-05',
  5,
  40.63,
  0.37,
  'P39CE1LT5.jpg',
  'EN',
  'EverGlow Butane',
  'Adjustable brightness control with auto ignition. Safely stores in its own protective case.  Approximate burn time 5 hours on one 0.25 liter butane canister, included.'),
 (40,
  '1995-02-15',
  5,
  17.97,
  0.28,
  'P40CE1LT5.jpg',
  'EN',
  'EverGlow Lamp',
  'Perfect for in your tent, this lamp comes with a 6V battery.  Complete with shade and hanging hook.'),
 (41,
  '2005-01-10',
  5,
  24.62,
  0.23,
  'P41CE1LT5.jpg',
  'EN',
  'Flicker Lantern',
  'Simple to use, just requires a candle to be inserted and lit.  Windproof, lasts for hours.'),
 (42,
  '2005-01-10',
  6,
  106.66,
  0.33,
  'P42ME2RP6.jpg',
  'EN',
  'Husky Rope 50',
  '11 mm diameter standard rope. Length: 50 m.  Weight: 78 g per meter. Impact Force: 7.2 kN. Static Elongation: 7.8%. Number of UIAA Falls: 16.'),
 (43,
  '2005-01-10',
  6,
  126.66,
  0.33,
  'P42ME2RP6.jpg',
  'EN',
  'Husky Rope 60',
  '11 mm diameter standard rope. Length: 60 m.  Weight: 78 g per meter. Impact Force: 7.2 kN. Static Elongation: 7.8%. Number of UIAA Falls: 16.'),
 (44,
  '2005-01-10',
  6,
  231.11,
  0.33,
  'P44ME2RP6.jpg',
  'EN',
  'Husky Rope 100',
  '11 mm diameter standard rope. Length: 100 m.  Weight: 78 g per meter. Impact Force: 7.2 kN. Static Elongation: 7.8%. Number of UIAA Falls: 16.'),
 (45,
  '2005-01-10',
  6,
  383.32,
  0.33,
  'P44ME2RP6.jpg',
  'EN',
  'Husky Rope 200',
  '11 mm diameter standard rope. Length: 200 m.  Weight: 78 g per meter. Impact Force: 7.2 kN. Static Elongation: 7.8%. Number of UIAA Falls: 16.'),
 (46,
  '2005-01-10',
  7,
  52.86,
  0.28,
  'P46ME2SY7.jpg',
  'EN',
  'Granite Climbing Helmet',
  'This UIAA approved helmet fits adults and kids, suitable for rock and alpine use.'),
 (47,
  '2005-01-10',
  7,
  44.83,
  0.31,
  'P47ME2SY7.jpg',
  'EN',
  'Husky Harness',
  'One size fits all due to extensive waist belt adjustment and fully adjustable leg loops.'),
 (48,
  '2005-01-10',
  7,
  55.0,
  0.5,
  'P47ME2SY7.jpg',
  'EN',
  'Husky Harness Extreme',
  'One size fits all. Top of the range fully adjustable technical harness. Ultra high strength belay loop rated in excess of 30kN. Rear haul loop rated to 10kN.'),
 (49,
  '2005-01-10',
  7,
  16.5,
  0.5,
  'P49ME2SY7.jpg',
  'EN',
  'Granite Signal Mirror',
  'Day or night signal mirror with gridded sighting hole.  6mm laminated glass. Soft carrying case included. Size: 8 x 13 cm. Weight: 400 g.'),
 (50,
  '2005-01-10',
  8,
  2.0,
  0.5,
  'P50ME2CA8.jpg',
  'EN',
  'Granite Carabiner',
  'Made from 12 mm rod stock aluminum and a radius suitable for almost any rope size. Locks tight with almost any belay/rappel combination. Individually tested.'),
 (51,
  '2005-01-10',
  8,
  35.0,
  0.5,
  'P51ME2CA8.jpg',
  'EN',
  'Granite Belay',
  'The Granite Belay is an ingenious single rope belay device that uses carabiner movement to brake the rope.'),
 (52,
  '2005-01-10',
  8,
  19.0,
  0.5,
  'P52ME2CA8.jpg',
  'EN',
  'Granite Pulley',
  'Light, simple and strong, a great all purpose pulley.'),
 (53,
  '2005-01-10',
  8,
  28.55,
  0.28,
  'P53ME2CA8.jpg',
  'EN',
  'Firefly Climbing Lamp',
  'This climbing lamp is water-resistant. It comes with two bulbs, standard and halogen. Includes one 6V halogen bulb and one 6V standard bulb. Weight: 200g.'),
 (54,
  '2005-01-10',
  8,
  35.33,
  0.33,
  'P54ME2CA8.jpg',
  'EN',
  'Firefly Charger',
  'Power charger for the Firefly Climbing Lamp. The charger cannot overcharge the Firefly battery, so you can leave it in the charger without worrying.'),
 (55,
  '2005-01-10',
  8,
  4.0,
  0.5,
  'P55ME2CA8.jpg',
  'EN',
  'Firefly Rechargeable Battery',
  'Rechargeable battery pack for the Firefly Climbing Lamp. Each charge gives 3 hours of light with a halogen bulb and 9 hours with standard bulb. Battery may be recharged up to 1,000 times.'),
 (56,
  '2005-01-10',
  8,
  9.0,
  0.5,
  'P56ME2CA8.jpg',
  'EN',
  'Granite Chalk Bag',
  'Nylon web bag perfect for holding several sticks of chalk.'),
 (57,
  '2005-01-10',
  9,
  40.0,
  0.5,
  'P57ME2TL9.jpg',
  'EN',
  'Granite Ice',
  'A general purpose mountaineering axe for snow and glacier travel. Excellent mid-weight axe. Weight: 638 g'),
 (58,
  '2005-01-10',
  9,
  57.13,
  0.28,
  'P58ME2TL9.jpg',
  'EN',
  'Granite Hammer',
  'A solid hammer made with a solid hard wood handle and steel head.  Weight: 800g.'),
 (59,
  '2005-01-10',
  9,
  46.15,
  0.23,
  'P59ME2TL9.jpg',
  'EN',
  'Granite Shovel',
  'Shovel has removable aluminum handle and heat treated aluminum blade.'),
 (60,
  '2005-01-10',
  9,
  10.0,
  0.5,
  'P60ME2TL9.jpg',
  'EN',
  'Granite Grip',
  'All-purpose stainless steel pliers. Sheath included. Length (closed) 12cm, (open) 16 cm. Weight: 200 g.'),
 (61,
  '2005-01-10',
  9,
  20.0,
  0.5,
  'P61ME2TL9.jpg',
  'EN',
  'Granite Axe',
  'Camping axe with clear coated wood handle.'),
 (62,
  '2005-01-10',
  9,
  47.06,
  0.4,
  'P62ME2TL9.jpg',
  'EN',
  'Granite Extreme',
  'The Edge Extreme is a collapsible plier-shaped gadget, three knife blades, file and scissors, perfect for the outdoors.  Carrying case included.'),
 (63,
  '1995-02-15',
  10,
  30.0,
  0.33,
  'P63PA3WT10.jpg',
  'EN',
  'Mountain Man Analog',
  'Padded leather strap, precision Swiss quartz movement, sweep second hand, 24-hour time ring, luminous hands and markers, hardened mineral crystal.'),
 (64,
  '1995-02-15',
  10,
  20.0,
  0.5,
  'P64PA3WT10.jpg',
  'EN',
  'Mountain Man Digital',
  'Tough rubber strap, digital face, hardened crystal, water-resistant to 50 meters.'),
 (65,
  '1997-03-05',
  10,
  39.0,
  0.5,
  'P65PA3WT10.jpg',
  'EN',
  'Mountain Man Deluxe',
  'Tough rubber strap, precision Swiss quartz movement, imbedded digital face, luminous hands and markers, hardened mineral crystal, start and stop buttons, water-resistant to 50 meters.'),
 (66,
  '1997-03-05',
  10,
  45.0,
  0.5,
  'P66PA3WT10.jpg',
  'EN',
  'Mountain Man Combination',
  'Combination watch, altimeter, compass and barometric gauge.  Heavy duty rubber strap,  hardened mineral crystal.'),
 (67,
  '2000-10-26',
  10,
  116.19,
  0.51,
  'P67PA3WT10.jpg',
  'EN',
  'Mountain Man Extreme',
  'Solid titanium case, crown, bezel.  Combination nylon and rubber strap. Analog representation on digital interface.  Backlit, hardened mineral crystal, water-resistant to 100 meters.'),
 (68,
  '1995-02-15',
  11,
  46.15,
  0.23,
  'P68PA3EW11.jpg',
  'EN',
  'Polar Sun',
  'The Polar Sun sunglasses have 3 mm thick lenses, which makes excellent protective eyewear for sport and safety.'),
 (69,
  '1995-02-15',
  11,
  73.33,
  0.33,
  'P69PA3EW11.jpg',
  'EN',
  'Polar Ice',
  'Polar Ice sunglasses have polarized lenses to combat glare from snow. Unbreakable nylon frame.'),
 (70,
  '1997-03-05',
  11,
  80.0,
  0.33,
  'P70PA3EW11.jpg',
  'EN',
  'Polar Sports',
  'Six base classic nylon composite frame sunglasses with wire core temples.'),
 (71,
  '1997-03-05',
  11,
  60.0,
  0.33,
  'P71PA3EW11.jpg',
  'EN',
  'Polar Wave',
  'Acrylex lenses in the Polar Wave sunglasses absorb up to 90% of visible light, 96% ultraviolet, and 82% infrared light. Unbreakable nylon frames.'),
 (72,
  '2000-10-26',
  11,
  72.5,
  0.5,
  'P72PA3EW11.jpg',
  'EN',
  'Polar Extreme',
  'Ideal for skiing and winter mountaineering. Frame is durable polyurethane with soft interior foam and adjustable woven elastic band providing an excellent fit. Weight: 139 g.'),
 (73,
  '1995-02-15',
  12,
  8.56,
  0.28,
  'P73PA3KV12.jpg',
  'EN',
  'Single Edge',
  'Single stainless steel blade folding knife. Length: (closed) 5 cm, (blade) 4.5 cm. Blade thickness 2 mm.  Weight: 90 g.'),
 (74,
  '1995-02-15',
  12,
  11.43,
  0.28,
  'P74PA3KV12.jpg',
  'EN',
  'Double Edge',
  'Double stainless steel blade folding knife. Length: (closed) 6 cm, (blades) 5.5 cm and 3 cm. Blade thickness: 2 mm. Weight: 110 g.'),
 (75,
  '2000-10-26',
  12,
  80.0,
  0.28,
  'P75PA3KV12.jpg',
  'EN',
  'Edge Extreme',
  'Multi-purpose pocketknife ruggedly constructed of stainless steel.  Includes 4 different blades, corkscrew, saw, scissors, pliers and more.'),
 (76,
  '1995-02-15',
  12,
  23.53,
  0.4,
  'P76PA3KV12.jpg',
  'EN',
  'Bear Edge',
  'Knife is 33 cm long with a 20 cm blade made of surgical stainless steel. The handle is laminated wood. The custom made sheath is black leather.'),
 (77,
  '2000-10-26',
  12,
  45.0,
  0.5,
  'P77PA3KV12.jpg',
  'EN',
  'Bear Survival Edge',
  'Features a 23 cm razor edge blade tempered from a special blend of stainless steel. The hollow handle has a compartment containing survival gear including a compass. Overall length: 36cm.'),
 (78,
  '1995-02-15',
  13,
  79.19,
  0.2,
  'P78PA3BN13.jpg',
  'EN',
  'Seeker 35',
  'This 7 x 35 model is economical and performs well optically. Fully coated lenses, compact and  lightweight. Rubber covered for secure and comfortable grip. Soft carrying case included.'),
 (79,
  '1995-02-15',
  13,
  92.58,
  0.25,
  'P78PA3BN13.jpg',
  'EN',
  'Seeker 50',
  'Rubber coated and ergonomically designed. The wide angle of view of 10 x 50 keeps more of your subject in view at high magnification. Soft carrying case included.'),
 (80,
  '1997-03-05',
  13,
  94.12,
  0.4,
  'P80PA3BN13.jpg',
  'EN',
  'Seeker Extreme',
  'These ergonomic binoculars are light-weight and easy to hold.  Strong construction make them impervious to water, fog and thermal shocks. Soft carrying case included.'),
 (81,
  '1997-03-05',
  13,
  40.0,
  0.5,
  'P81PA3BN13.jpg',
  'EN',
  'Seeker Mini',
  'This 8 x 22 model is economical and performs well optically. Fully coated lenses, compact and  light-weight. Rubber covered for secure and comfortable grip. Soft carrying case included.'),
 (82,
  '1997-03-05',
  14,
  20.0,
  0.33,
  'P82PA3NV14.jpg',
  'EN',
  'Glacier Basic',
  'Traditional magnetic compass in a stainless steel casing.'),
 (83,
  '1997-03-05',
  14,
  56.25,
  0.37,
  'P83PA3NV14.jpg',
  'EN',
  'Glacier Deluxe',
  'Magnetic Compass has a large sighting mirror with v-notch allowing for quick acquisition and accurate bearings to distant landmarks.'),
 (84,
  '1997-03-05',
  14,
  78.55,
  0.28,
  'P84PA3NV14.jpg',
  'EN',
  'Glacier GPS',
  'Global Positioning System that is small, lightweight, and rugged. Incredibly easy to use, dedicated operation keys, and three user-friendly navigation screens.'),
 (85,
  '1999-06-12',
  14,
  176.47,
  0.4,
  'P85PA3NV14.jpg',
  'EN',
  'Glacier GPS Extreme',
  'Hand held GPS receiver with color display. Incredibly easy to use, three user-friendly navigation screens, and saves two routes. Up to 20 hours of battery life just on two AA batteries.'),
 (86,
  '1995-02-15',
  15,
  2.0,
  0.67,
  'P86OP4IR15.jpg',
  'EN',
  'BugShield Natural',

Krijg je een "no such table" error? Dan heb je misschien met .connect() per ongeluk een leeg  databasebestand (.sqlite) aangemaakt. <u>Let op:</u> lees eventueel de informatie uit het Notebook van werkcollege 1.1b nog eens goed door.

Als je tijdens onderstaande opdrachten uit het oog verliest welke tabellen er allemaal zijn, kan je deze Pythoncode uitvoeren:

In [113]:
sql_query = "SELECT name FROM sqlite_master WHERE type='table';"

#Vul dit codeblok verder in
pd.read_sql(sql_query, sqlite3.connect('go_sales_train.sqlite'))
#Op de puntjes hoort de connectie naar go_sales_train óf go_staff_train óf go_crm_train te staan.

             name
0         country
1   order_details
2    order_header
3    order_method
4         product
5    product_line
6    product_type
7   retailer_site
8   return_reason
9   returned_item
10   sales_branch
11    sales_staff

erachter

Let op! Voor alle onderstaande opdrachten mag je <u>alleen Python</u> gebruiken, <u>geen SQL!</u>

## Selecties op één tabel zonder functies

Geef een overzicht met daarin de producten en hun productiekosten waarvan de productiekosten lager dan 100 dollar en hoger dan 50 dollar ligt. (2 kolommen, 23 rijen)

In [114]:
sales = cursor.execute("SELECT * FROM product")
result = cursor.fetchall()

column_names = [desc[0] for desc in cursor.description]
sales_table = pd.DataFrame(result, columns=column_names)
v1 = sales_table[(sales_table['PRODUCT_NUMBER'] < 100) & ( sales_table['PRODUCTION_COST'] > 50)]
v1.loc[:, ['PRODUCT_NUMBER', 'PRODUCTION_COST']]
# sales_table

    PRODUCT_NUMBER  PRODUCTION_COST
5                6            85.11
7                8            75.00
10              11           250.00
11              12           473.07
12              13           392.57
13              14           476.00
14              15           490.00
16              17            60.00
17              18            86.00
18              19           150.00
19              20            78.55
22              23            65.33
23              24            62.50
24              25           166.66
25              26           213.33
26              27           238.88
41              42           106.66
42              43           126.66
43              44           231.11
44              45           383.32
45              46            52.86
47              48            55.00
57              58            57.13
66              67           116.19
68              69            73.33
69              70            80.00
70              71            60.00
71              72            72.50
74              75            80.00
77              78            79.19
78              79            92.58
79              80            94.12
82              83            56.25
83              84            78.55
84              85           176.47

Geef een overzicht met daarin de producten en hun marge waarvan de marge lager dan 20 % of hoger dan 60 % ligt. (2 kolommen, 7 rijen)

In [115]:
v2 = sales_table[(sales_table['MARGIN'] < 0.20) | (sales_table['MARGIN'] > 0.60)]
v2.loc[:, ['PRODUCT_NUMBER', 'MARGIN']]

    PRODUCT_NUMBER  MARGIN
20              21    0.17
23              24    0.17
85              86    0.67
86              87    0.67
87              88    0.70
88              89    0.63
89              90    0.63

Geef een overzicht met daarin de landen waar met francs wordt betaald. Sorteer de uitkomst op land.  (1 kolom, 3 rijen)

In [116]:
cursor.execute("SELECT * FROM country")
result = cursor.fetchall()

column_names = [desc[0] for desc in cursor.description]
landen_table = pd.DataFrame(result, columns=column_names)
v3 = landen_table[(landen_table['CURRENCY_NAME'] == 'francs')]
v3.groupby(['COUNTRY', 'CURRENCY_NAME', 'COUNTRY_CODE']).mean(numeric_only=True)

Empty DataFrame
Columns: []
Index: [(Belgium, francs, 17), (France, francs, 1), (Switzerland, francs, 8)]

Geef een overzicht met daarin de verschillende introductiedatums waarop producten met meer dan 50% marge worden geïntroduceerd (1 kolom, 7 rijen)

In [117]:
v4 = sales_table[(sales_table['MARGIN'] > 0.50)]
v4 = v4.loc[:, ['INTRODUCTION_DATE', 'MARGIN']].drop_duplicates('INTRODUCTION_DATE')
v4

    INTRODUCTION_DATE  MARGIN
66         2000-10-26    0.51
85         1995-02-15    0.67
101        2003-12-10    0.51
103        2003-12-18    0.51
104        2003-12-27    0.55
106        2004-01-13    0.55
110        2003-12-15    0.55

Geef een overzicht met daarin het eerste adres en de stad van verkoopafdelingen waarvan zowel het tweede adres als de regio bekend is (2 kolommen, 7 rijen)

In [118]:
cursor.execute("SELECT * FROM sales_branch")
sb = cursor.fetchall()

column_names = [desc[0] for desc in cursor.description]
salesBranch_table = pd.DataFrame(sb, columns=column_names)


v5 = salesBranch_table
addressRegionFilter = salesBranch_table[['ADDRESS2', 'REGION']].notna().all(axis=1)
v5.loc[(addressRegionFilter), ['ADDRESS1', 'CITY']]

                            ADDRESS1              CITY
2                Singelgravenplein 4         Amsterdam
13  Prol. Paseo de la Reforma No. 51  Distrito Federal
14               202-2-3 Hyakunincho             Tokyo
15                     543-225 Asahi        Osaka City
16                  2315 Queen's Ave         Melbourne
18             Avenida Paulista, 333         São Paulo
24                    3 Albany Court        Birmingham

Geef een overzicht met daarin de landen waar met dollars (dollars of new dollar) wordt betaald. Sorteer de uitkomst op land. (1 kolom, 4 rijen)

In [119]:
v6 = landen_table[(landen_table['CURRENCY_NAME'] == 'dollars') | (landen_table['CURRENCY_NAME'] == 'new dollar')]
v6 = v6.groupby(['COUNTRY', 'COUNTRY_CODE']).mean(numeric_only=True)

v6

Empty DataFrame
Columns: []
Index: [(Australia, 16), (Canada, 4), (Taiwan, 12), (United States, 3)]

Geef een overzicht met daarin beide adressen en de stad van vestigingen van klanten waarvan de postcode begint met een ‘D’ (van duitsland). Filter op vestigingen die een tweede adres hebben. (3 kolommen, 2 rijen)

In [120]:
v7 = salesBranch_table[(salesBranch_table['POSTAL_ZONE'].str.startswith('D', na=False))]
v7 = v7.loc[:, ['ADDRESS1', 'ADDRESS2', 'CITY']]
v7

           ADDRESS1 ADDRESS2     CITY
3    Schwabentor 35     None  Hamburg
4  Leopoldstraße 36     None  München

## Selecties op één tabel met functies

Geef het totaal aantal producten dat is teruggebracht (1 waarde)

In [121]:
cursor.execute("SELECT * FROM returned_item")
ri = cursor.fetchall()

column_names = [desc[0] for desc in cursor.description]
returned_items = pd.DataFrame(ri, columns=column_names)

v8 = returned_items

v8['RETURN_QUANTITY'].sum()

np.int64(11908)

Geef het aantal regio’s waarin verkoopafdelingen gevestigd zijn. (1 waarde)

In [122]:
cursor.execute("SELECT * FROM sales_branch")
sb2 = cursor.fetchall()

column_names = [desc[0] for desc in cursor.description]
v9 = pd.DataFrame(sb2, columns=column_names)
v9['CITY'].count()

np.int64(28)

Maak 3 variabelen:
- Een met de laagste
- Een met de hoogste
- Een met de gemiddelde (afgerond op 2 decimalen)

marge van producten (3 kolommen, 1 rij)

In [123]:
cursor.execute("SELECT * FROM product")
p1 = cursor.fetchall()

column_names = [desc[0] for desc in cursor.description]
v10 = pd.DataFrame(p1, columns=column_names)
var1 = v10['MARGIN'].min()
var2 = v10['MARGIN'].max()
var3 = round(v10['MARGIN'].mean(), 2)

result = pd.DataFrame({
    'Laagste' : [var1],
    'Hoogste' : [var2],
    'Gemiddelde' : [var3]
})

result

   Laagste  Hoogste  Gemiddelde
0     0.17      0.7         0.4

Geef het aantal vestigingen van klanten waarvan het 2e adres niet bekend is (1 waarde)

In [124]:
cursor.execute("SELECT * FROM sales_branch")
p2 = cursor.fetchall()

column_names = [desc[0] for desc in cursor.description]
v11 = pd.DataFrame(p2, columns=column_names)
v11[v11['ADDRESS2'].isnull()]['SALES_BRANCH_CODE'].count()

np.int64(19)

Geef de gemiddelde kostprijs van de verkochte producten waarop korting (unit_sale_price < unit_price) is verleend (1 waarde)

In [125]:
cursor.execute("SELECT * FROM order_details")
od1 = cursor.fetchall()

column_names = [desc[0] for desc in cursor.description]
v12 = pd.DataFrame(od1, columns=column_names)
v12 = v12[v12['UNIT_PRICE'] > v12['UNIT_SALE_PRICE']]

v12['UNIT_COST'].mean()

np.float64(127.34087927598804)

Geef een overzicht met daarin het aantal medewerkers per medewerkersfunctie (2 kolommen, 7 rijen)

In [126]:
cursor.execute("SELECT * FROM sales_staff")
sb3 = cursor.fetchall()

column_names = [desc[0] for desc in cursor.description]
v13 = pd.DataFrame(sb3, columns=column_names)

v13.groupby('POSITION_EN').size().reset_index(name='Aantal Medewerkers')

                    POSITION_EN  Aantal Medewerkers
0                Branch Manager                  19
1              District Manager                   4
2               General Manager                   1
3  Level 1 Sales Representative                  13
4  Level 2 Sales Representative                  39
5  Level 3 Sales Representative                  24
6              Regional Manager                   2

Geef een overzicht met daarin per telefoonnummer het aantal medewerkers dat op dat telefoonnummer bereikbaar is. Toon alleen de telefoonnummer waarop meer dan 4 medewerkers bereikbaar zijn. (2 kolommen, 10 rijen)

In [127]:
cursor.execute("SELECT * FROM sales_staff")
sb3 = cursor.fetchall()

column_names = [desc[0] for desc in cursor.description]
v13 = pd.DataFrame(sb3, columns=column_names)

v13 = v13.groupby('WORK_PHONE').size().reset_index(name='Aantal Medewerkers')
v13[v13['Aantal Medewerkers'] > 4]

             WORK_PHONE  Aantal Medewerkers
4     +(44) 121 3505267                   5
10  +(61) 03 2982  4242                   5
11  +31 (0)20 692 93 94                   5
13    +33 1 68 94 52 20                   5
18     1 (206) 292-0012                   5
19     1 (305) 557-4810                   6
20     1 (310) 281-5722                   5
21     1 (403) 232-5986                   5
22     1 (416) 493-5595                   5
23     1 (617) 268-6754                   6

## Selecties op meerdere tabellen zonder functies

Geef een overzicht met daarin het eerste adres en de stad van vestigingen van klanten uit ‘Netherlands’ (2 kolommen, 20 rijen)

In [128]:
land = pd.read_sql_query("SELECT * FROM COUNTRY", sqliteConnection)
retailer = pd.read_sql_query("SELECT * FROM retailer_site", sqliteConnection) 

merge = pd.merge(land, retailer, on="COUNTRY_CODE")

v13 = merge[merge['COUNTRY'] == 'Netherlands']
v13.loc[:, ['ADDRESS1', 'CITY']]

                      ADDRESS1          CITY
215                   Beets 36         Beets
216               Perestraat 1      Deventer
217  Laan van Meerdervoort 966      Den Haag
218             Kalfjeslaan 47    Amstelveen
219               Startbaan 11    Amstelveen
220      Noorderspoorsingel 28     Groningen
221              Hogehilweg 13     Amsterdam
222             Spoorstraat 43    Varsseveld
223             Westhavenweg 8     Amsterdam
224              Westzeedijk 4        Muiden
225            Gooiergracht 91         Laren
226            Hoofdstraat 150   Pieterburen
227                Olde Diek 2         Laren
228     Amsterdamsestraatweg 8      Maarssen
229        Krayenhoffstraat 11     Amsterdam
230         Overschiestraat 19     Amsterdam
231              Havenbuurt 12        Marken
232               Duivendaal 1    Wageningen
233              Voorstraat 37  Nieuweschans
234         Stadhouderslaan 18     Rotterdam

Geef een overzicht met daarin de productnamen die tot het producttype ‘Eyewear’ behoren. (1 kolom, 5 rijen)

In [129]:
product = pd.read_sql_query("SELECT * FROM PRODUCT", sqliteConnection)
producttype = pd.read_sql_query("SELECT * FROM PRODUCT_TYPE", sqliteConnection)

productmerge = pd.merge(product, producttype, on='PRODUCT_TYPE_CODE')
productmerge[productmerge['PRODUCT_TYPE_EN'] == 'Eyewear'][['PRODUCT_NAME']]

     PRODUCT_NAME
67      Polar Sun
68      Polar Ice
69   Polar Sports
70     Polar Wave
71  Polar Extreme

Geef een overzicht met daarin alle unieke eerste adressen van klantvestigingen en de voornaam en achternaam van de verkopers die ‘Branch Manager’ zijn en aan deze vestigingen hebben verkocht (3 kolommen, 1 rij)

In [130]:
staff = pd.read_sql_query('SELECT * FROM sales_staff', sqliteConnection)
branch = pd.read_sql_query('SELECT * FROM sales_branch', sqliteConnection)
header = pd.read_sql_query("SELECT * FROM order_header", sqliteConnection)

merge1 = pd.merge(branch, staff, on='SALES_BRANCH_CODE')

branchManager = merge1[merge1['POSITION_EN'] == 'Branch Manager']
branchManager.loc[:, ['ADDRESS1', 'FIRST_NAME', 'LAST_NAME']].drop_duplicates()

                            ADDRESS1 FIRST_NAME      LAST_NAME
0      75, rue du Faubourg St-Honoré      Denis           Pagé
5                    Piazza Duomo, 1      Maria      Iacobucci
10               Singelgravenplein 4       Kick        Kalkman
14                    Schwabentor 35      Frank          Fuchs
17                  Leopoldstraße 36      Fritz         Hirsch
22               Isafjordsgatan 30 C      Karin      Bergström
25      7800, 756 - 6th Avenue. S.W.      Sally          White
28                  789 Yonge Street    Georges  Saint-Germain
33            1288 Dorchester Avenue       Alex      Rodriguez
39                   299 Yale Avenue   Samantha          Floyd
44        1288 South Barrington Ave.      Corey         Wright
50                    10032 NW 186th      Julie          Olsen
55               6c, rue de l'Église      Julie        Béchard
59  Prol. Paseo de la Reforma No. 51      Lucía          Reyna
66                  2315 Queen's Ave      Alice         Walter
73             Avenida Paulista, 333     Bayard          Lopes
84                    Victoria House     Walter         Taylor
88                    3 Albany Court      Polly         Linton
96                 Interleuvenlaan 2      Gracy        Gellens

Geef een overzicht met daarin van de verkopers hun functie en indien zij iets hebben verkocht de datum waarop de verkoop heeft plaatsgevonden. Laat alleen de verschillende namen van de posities zien van de verkopers die het woord ‘Manager’ in hun positienaam hebben staan. (2 kolommen, 7 rijen)

In [131]:
staff = pd.read_sql_query('SELECT * FROM sales_staff', sqliteConnection)
branch = pd.read_sql_query('SELECT * FROM sales_branch', sqliteConnection)
header = pd.read_sql_query("SELECT * FROM order_header", sqliteConnection)

merge2 = pd.merge(branch, staff, on='SALES_BRANCH_CODE')
merge3 = pd.merge(merge2, header, right_on='SALES_STAFF_CODE', left_on='SALES_STAFF_CODE')

branchManager2 = merge3[merge3['POSITION_EN'].str.contains('Manager', na=False)]
branchManager2.loc[:, ['POSITION_EN', 'ORDER_DATE']].drop_duplicates()

         POSITION_EN  ORDER_DATE
3727  Branch Manager  2024-09-09
3728  Branch Manager  2024-03-13
3729  Branch Manager  2024-01-09

Geef een overzicht met daarin de verschillende namen van producten en bijbehorende namen van producttypen van de producten waarvoor ooit meer dan 750 stuks tegelijk verkocht zijn. (2 kolommen, 9 rijen)

In [132]:
product = pd.read_sql_query('SELECT * FROM PRODUCT', sqliteConnection)
orderDetails = pd.read_sql_query('SELECT * FROM ORDER_DETAILS', sqliteConnection)
productType = pd.read_sql_query("SELECT * FROM PRODUCT_TYPE", sqliteConnection)

merge4 = pd.merge(product, orderDetails, on='PRODUCT_NUMBER')
merge5 = pd.merge(merge4, productType, on='PRODUCT_TYPE_CODE')

merge5[merge5['QUANTITY'] > 750][['PRODUCT_NAME', 'PRODUCT_TYPE_EN']].drop_duplicates()

                PRODUCT_NAME    PRODUCT_TYPE_EN
5427                Star Peg              Tents
11452              Firefly 2           Lanterns
28608        BugShield Spray  Insect Repellents
28892  BugShield Lotion Lite  Insect Repellents
29430       BugShield Lotion  Insect Repellents
29442      BugShield Extreme  Insect Repellents
30741         Sun Shelter 15          Sunscreen
31164         Sun Shelter 30          Sunscreen
31775             Sun Shield          Sunscreen

Geef een overzicht met daarin de productnamen waarvan ooit meer dan 40% korting is verleend. De formule voor korting is: (unit_price - unit_sale_price) / unit_price (1 kolom, 8 rijen)

In [133]:
orderDetails = pd.read_sql_query("SELECT * FROM order_details", sqliteConnection)
product = pd.read_sql_query("SELECT * FROM product", sqliteConnection)

merge6 = pd.merge(orderDetails, product, on='PRODUCT_NUMBER')

merge6['DISCOUNT'] = (merge6['UNIT_PRICE'] - merge6['UNIT_SALE_PRICE']) / merge6['UNIT_PRICE']
merge6[merge6['DISCOUNT'] > 0.40][['PRODUCT_NAME']].drop_duplicates()

                      PRODUCT_NAME
506              BugShield Natural
511                BugShield Spray
650   Hailstorm Titanium Woods Set
2797         BugShield Lotion Lite
2836                Sun Shelter 30
3751             BugShield Extreme
5074                Sun Shelter 15
6930              BugShield Lotion

Geef een overzicht met daarin de retourreden van producten waarvan ooit meer dan 90% van de aangeschafte hoeveelheid is teruggebracht (return_quantity/quantity). (1 kolom, 3 rijen)

In [134]:
orderDetails = pd.read_sql_query("SELECT * FROM order_details", sqliteConnection)
product = pd.read_sql_query("SELECT * FROM product", sqliteConnection)
returnedItems = pd.read_sql_query("SELECT * FROM returned_item", sqliteConnection)
returnReasons = pd.read_sql_query("SELECT * FROM return_reason", sqliteConnection)

merge7 = pd.merge(orderDetails, product, on='PRODUCT_NUMBER')
merge8 = pd.merge(merge7, returnedItems, on='ORDER_DETAIL_CODE')
merge9 = pd.merge(merge8, returnReasons, on='RETURN_REASON_CODE')

retourreden = merge9[(merge9['RETURN_QUANTITY'] / merge9['QUANTITY']) > 0.90]['RETURN_DESCRIPTION_EN'].drop_duplicates()
retourreden

0     Wrong product ordered
4     Wrong product shipped
5    Unsatisfactory product
Name: RETURN_DESCRIPTION_EN, dtype: object

## Selecties op meerdere tabellen met functies

Geef een overzicht met daarin per producttype het aantal producten die tot dat producttype behoren. (2 kolommen, 21 rijen)

In [135]:
product = pd.read_sql_query("SELECT * FROM product", sqliteConnection)
productType = pd.read_sql_query("SELECT * FROM product_type", sqliteConnection)
merge10 = pd.merge(product, productType, on='PRODUCT_TYPE_CODE')

merge10.groupby('PRODUCT_TYPE_EN').size()

PRODUCT_TYPE_EN
Binoculars               4
Climbing Accessories     7
Cooking Gear            10
Eyewear                  5
First Aid                5
Golf Accessories         4
Insect Repellents        5
Irons                    4
Knives                   5
Lanterns                12
Navigation               4
Packs                    6
Putters                  3
Rope                     4
Safety                   4
Sleeping Bags            7
Sunscreen                5
Tents                    6
Tools                    6
Watches                  5
Woods                    4
dtype: int64

Geef een overzicht met daarin per land het aantal vestigingen van klanten die zich in dat land bevinden. (2 kolommen, 21 rijen)

In [136]:
retailerSite = pd.read_sql_query("SELECT * FROM retailer_site", sqliteConnection)
country = pd.read_sql_query("SELECT * FROM country", sqliteConnection)
merge11 = pd.merge(retailerSite, country, on='COUNTRY_CODE')
merge11.groupby('COUNTRY').size()

COUNTRY
Australia          10
Austria            10
Belgium            10
Brazil              1
Canada             31
China              10
Denmark             6
Finland             5
France             29
Germany            32
Italy              12
Japan              25
Korea              10
Mexico             10
Netherlands        20
Spain               9
Sweden             12
Switzerland        13
Taiwan             10
United Kingdom     25
United States     101
dtype: int64

Geef een overzicht met daarin van de producten behorend tot het producttype ‘Cooking Gear’ per productnaam de totaal verkochte hoeveelheid en de gemiddelde verkoopprijs. Sorteer de uitkomst op totaal verkochte hoeveelheid. (4 kolommen, 10 rijen)

In [137]:
product = pd.read_sql_query("SELECT * FROM product", sqliteConnection)
productType = pd.read_sql_query("SELECT * FROM product_type", sqliteConnection)
merge12 = pd.merge(product, productType, on='PRODUCT_TYPE_CODE')
merge12 = merge12[merge12['PRODUCT_TYPE_EN'] == 'Cooking Gear']

orderDetails = pd.read_sql_query("SELECT * FROM order_details", sqliteConnection)
merge13 = pd.merge(merge12, orderDetails, on='PRODUCT_NUMBER')
merge13 = merge13.groupby(['PRODUCT_NAME', 'PRODUCT_TYPE_EN']).agg({'QUANTITY': 'sum', 'UNIT_SALE_PRICE': 'mean'})
merge13.sort_values(by='QUANTITY', ascending=False).reset_index()

                PRODUCT_NAME PRODUCT_TYPE_EN  QUANTITY  UNIT_SALE_PRICE
0        TrailChef Water Bag    Cooking Gear     36738         6.032506
1              TrailChef Cup    Cooking Gear     27418         6.976490
2          TrailChef Canteen    Cooking Gear     26544        11.979418
3      TrailChef Kitchen Kit    Cooking Gear     22206        22.345975
4         TrailChef Utensils    Cooking Gear     13776        17.294151
5     TrailChef Double Flame    Cooking Gear     12476       132.672882
6         TrailChef Cook Set    Cooking Gear     10878        51.687926
7           TrailChef Kettle    Cooking Gear      8826        12.201235
8     TrailChef Single Flame    Cooking Gear      8504        63.827622
9  TrailChef Deluxe Cook Set    Cooking Gear      3110       121.217638

Geef een overzicht met daarin per land de naam van het land, de naam van de stad waar de verkoopafdeling is gevestigd (noem de kolomnaam in het overzicht ‘verkoper’) en het aantal steden waar zich klanten bevinden in dat land (noem de kolomnaam in het overzicht ‘klanten’) (3 kolommen, 29 rijen)

In [138]:
retailerSite = pd.read_sql_query("SELECT * FROM retailer_site", sqliteConnection)
country = pd.read_sql_query("SELECT * FROM country", sqliteConnection)
merge14 = pd.merge(retailerSite, country, on='COUNTRY_CODE')

merge14.groupby(['COUNTRY']).agg(
    verkoper=pd.NamedAgg(column='CITY', aggfunc='first'),
    klanten=pd.NamedAgg(column='CITY', aggfunc='count')
).reset_index()

           COUNTRY      verkoper  klanten
0        Australia     Melbourne       10
1          Austria          Wien       10
2          Belgium      Zaventem       10
3           Brazil     São Paulo        1
4           Canada      Winnipeg       31
5            China       Beijing       10
6          Denmark     København        6
7          Finland       Tampere        5
8           France         Paris       29
9          Germany     Frankfurt       32
10           Italy       Bologna       12
11           Japan     Osaka-shi       25
12           Korea         Pusan       10
13          Mexico        Cancún       10
14     Netherlands         Beets       20
15           Spain     Barcelona        9
16          Sweden     Stockholm       12
17     Switzerland         Basel       13
18          Taiwan  Chungho City       10
19  United Kingdom        London       25
20   United States      Hartford      101

## Pythonvertalingen van SUBSELECT en UNION met o.a. for-loops

Geef een overzicht met daarin de voornaam en de achternaam van de medewerkers die nog nooit wat hebben verkocht (2 kolommen, 25 rijen)

In [139]:
salesStaff = pd.read_sql_query("SELECT * FROM sales_staff", sqliteConnection)
orderHeader = pd.read_sql_query("SELECT * FROM order_header", sqliteConnection)

hasSales = orderHeader['SALES_STAFF_CODE'].unique()
noSales = salesStaff[-salesStaff['SALES_STAFF_CODE'].isin(hasSales)]
noSales[['FIRST_NAME', 'LAST_NAME']]

   FIRST_NAME      LAST_NAME
0       Denis           Pagé
5        Else         Mörike
6       Frank          Fuchs
9       Fritz         Hirsch
10       Jörg          Kunze
12      Maria      Iacobucci
17       Kick        Kalkman
22      Karin      Bergström
25      Sally          White
27      Frank        Bretton
28    Georges  Saint-Germain
33       Alex      Rodriguez
37   Samantha          Floyd
41      Julie          Olsen
45      Corey         Wright
51    Estelle        Johnson
52       Greg        Belding
55      Julie        Béchard
59      Lucía          Reyna
64     Kazumi        Uragome
66      Alice         Walter
84     Walter         Taylor
85   Penelope        Tamrine
88      Polly         Linton
96      Gracy        Gellens

Geef een overzicht met daarin het aantal producten waarvan de marge lager is dan de gemiddelde marge van alle producten samen. Geef in het overzicht tevens aan wat de gemiddelde marge is van dit aantal producten waarvan de marge lager dan de gemiddelde marge van alle producten samen is. (1 kolom, 2 rijen)

In [140]:
product = pd.read_sql_query("SELECT * FROM product", sqliteConnection)
avg_marge = product['MARGIN'].mean()
count_product_avg_marge = len(product[product['MARGIN'] < avg_marge])
overzicht = pd.DataFrame({
    'Aantal_producten': [count_product_avg_marge],
    'Avg_margin' : [avg_marge]
})
overzicht

   Aantal_producten  Avg_margin
0                59    0.396609

Geef een overzicht met daarin de namen van de producten die voor meer dan 500 (verkoopprijs) zijn verkocht maar nooit zijn teruggebracht. (1 kolom, 13 rijen)

In [141]:
product = pd.read_sql_query("SELECT * FROM product", sqliteConnection)
orderDetails = pd.read_sql_query("SELECT * FROM order_details", sqliteConnection)
sold_products = orderDetails[orderDetails['UNIT_SALE_PRICE'] > 500]
product_orderDetails = pd.merge(product, sold_products, on='PRODUCT_NUMBER')

returned_item = pd.read_sql_query("SELECT * FROM returned_item", sqliteConnection)
product_orderDetails_returnedItem = pd.merge(product_orderDetails, returned_item, on='ORDER_DETAIL_CODE')

product_orderDetails_result = product_orderDetails[-product_orderDetails['ORDER_DETAIL_CODE'].isin(product_orderDetails_returnedItem)]
product_orderDetails_result['PRODUCT_NAME'].drop_duplicates()

0                               Star Dome
397                          Star Gazer 2
575                          Star Gazer 3
961                          Star Gazer 6
1284                       Husky Rope 200
1450                Hailstorm Steel Irons
1761             Hailstorm Titanium Irons
2125           Lady Hailstorm Steel Irons
2286        Lady Hailstorm Titanium Irons
2549         Hailstorm Titanium Woods Set
2844            Hailstorm Steel Woods Set
3229    Lady Hailstorm Titanium Woods Set
3508       Lady Hailstorm Steel Woods Set
Name: PRODUCT_NAME, dtype: object

Geef een overzicht met daarin per (achternaam van) medewerker of hij/zij manager is of niet, door deze informatie toe te voegen als extra 'Ja/Nee'-kolom.<br>
Hint: gebruik een for-loop waarin je o.a. bepaalt of het woord 'Manager' in de functie (position_en) staat. (2 kolommen, 102 rijen).

In [142]:
salesStaff = pd.read_sql_query("SELECT * FROM sales_staff", sqliteConnection)

is_manager = []
for position in salesStaff['POSITION_EN']:
    if 'Manager' in position:
        is_manager.append('Ja')
    else:
        is_manager.append('Nee')

salesStaff['IS_MANAGER'] = is_manager

overzicht = salesStaff[['LAST_NAME', 'IS_MANAGER']]

overzicht

     LAST_NAME IS_MANAGER
0         Pagé         Ja
1       Michel        Nee
2     Clermont        Nee
3       Jauvin        Nee
4    Wiesinger        Nee
..         ...        ...
97    Laermans        Nee
98     De Crée        Nee
99     Lattrez        Nee
100  Seefelder        Nee
101     Grüner        Nee

[102 rows x 2 columns]

Met de onderstaande code laat je Python het huidige jaar uitrekenen.

In [143]:
from datetime import date
date.today().year

2025

Met de onderstaande code selecteer je op een bepaald jaartal uit een datum.

In [144]:
from datetime import datetime

date_str = '16-8-2013'
date_format = '%d-%m-%Y'
date_obj = datetime.strptime(date_str, date_format)

date_obj.year

2013

Geef met behulp van bovenstaande hulpcode een overzicht met daarin op basis van het aantal jaar dat iemand in dienst is of een medewerker ‘kort in dienst’ (minder dan 25 jaar in dienst) of een ‘lang in dienst’ (groter gelijk dan 12 jaar in dienst) is. Geef daarbij per medewerker in een aparte kolom zowel ‘kort in dienst’ als ‘lang in dienst’ aan. Gebruik (wederom) een for-loop.<br>
(2 kolommen, 102 rijen)

In [145]:
from datetime import datetime, date
salesStaff = pd.read_sql_query("SELECT * FROM sales_staff", sqliteConnection)

dienstJaren = []
for dienstDate in salesStaff['DATE_HIRED']:
    dienstJaren.append(date.today().year - datetime.strptime(dienstDate, '%Y-%m-%d').year)

salesStaff['SERVICE_YEARS'] = dienstJaren

kort_in_dienst = []
lang_in_dienst = []

for years in salesStaff['SERVICE_YEARS']:
    if years < 25:
        kort_in_dienst.append('Ja')
    else:
        kort_in_dienst.append('Nee')

    if years >= 12:
        lang_in_dienst.append('Ja')
    else:
        lang_in_dienst.append('Nee')

salesStaff['KORT_IN_DIENST'] = kort_in_dienst
salesStaff['LANG_IN_DIENST'] = lang_in_dienst


overzicht_dienst = salesStaff[['LAST_NAME', 'KORT_IN_DIENST', 'LANG_IN_DIENST']]

pd.set_option('display.max_rows', None)

overzicht_dienst

            LAST_NAME KORT_IN_DIENST LANG_IN_DIENST
0                Pagé            Nee             Ja
1              Michel            Nee             Ja
2            Clermont            Nee             Ja
3              Jauvin            Nee             Ja
4           Wiesinger            Nee             Ja
5              Mörike            Nee             Ja
6               Fuchs            Nee             Ja
7               Erler            Nee             Ja
8             Winkler            Nee             Ja
9              Hirsch            Nee             Ja
10              Kunze            Nee             Ja
11          Allessori            Nee             Ja
12          Iacobucci            Nee             Ja
13              Torta            Nee             Ja
14   Jansen-Velasquez            Nee             Ja
15            Shapiro            Nee             Ja
16          Haverkamp            Nee             Ja
17            Kalkman            Nee             Ja
18           Laponder            Nee             Ja
19            Nilsson            Nee             Ja
20             Gradin            Nee             Ja
21     Engelbrektsson            Nee             Ja
22          Bergström            Nee             Ja
23             Vachon            Nee             Ja
24           Townsend            Nee             Ja
25              White            Nee             Ja
26            Rowland            Nee             Ja
27            Bretton            Nee             Ja
28      Saint-Germain            Nee             Ja
29            Claudel            Nee             Ja
30               Chow            Nee             Ja
31             Pierce            Nee             Ja
32               Pike            Nee             Ja
33          Rodriguez            Nee             Ja
34             Wilcox            Nee             Ja
35             Lavoie            Nee             Ja
36           Cummings            Nee             Ja
37              Floyd            Nee             Ja
38          McCormick            Nee             Ja
39            Lastman            Nee             Ja
40              Scott            Nee             Ja
41              Olsen            Nee             Ja
42           Chambers            Nee             Ja
43           Michaels            Nee             Ja
44            Hoffman            Nee             Ja
45             Wright            Nee             Ja
46             Fowler            Nee             Ja
47            Johnson            Nee             Ja
48           Lewiston            Nee             Ja
49             Carson            Nee             Ja
50              Cohen            Nee             Ja
51            Johnson            Nee             Ja
52            Belding            Nee             Ja
53           Germaine            Nee             Ja
54             Thomas            Nee             Ja
55            Béchard            Nee             Ja
56             Martin            Nee             Ja
57             Turpin            Nee             Ja
58             Samson            Nee             Ja
59              Reyna            Nee             Ja
60             Orozco            Nee             Ja
61              Rojas            Nee             Ja
62              Iseya            Nee             Ja
63              Imori            Nee             Ja
64            Uragome            Nee             Ja
65              Kakui            Nee             Ja
66             Walter            Nee             Ja
67             Smythe            Nee             Ja
68               Ward            Nee             Ja
69             Cartel            Nee             Ja
70             Sinden            Nee             Ja
71             Torres            Nee             Ja
72           Iglesias            Nee             Ja
73              Lopes            Nee             Ja
74             Barros             Ja             Ja
75          Guimarães            Nee             Ja
76           Lindholm            Nee             Ja
77         Savolainen            Nee             Ja
78                Kim            Nee             Ja
79               Choi            Nee             Ja
80                Kao            Nee             Ja
81               Fang            Nee             Ja
82               Wang            Nee             Ja
83               Meng            Nee             Ja
84             Taylor            Nee             Ja
85            Tamrine            Nee             Ja
86         Willoughby            Nee             Ja
87         Ross-Hythe            Nee             Ja
88             Linton            Nee             Ja
89              Lopez            Nee             Ja
90               Reed            Nee             Ja
91             Walker            Nee             Ja
92             Browne            Nee             Ja
93             Sommer            Nee             Ja
94              Jever            Nee             Ja
95          Vertemati            Nee             Ja
96            Gellens            Nee             Ja
97           Laermans            Nee             Ja
98            De Crée            Nee             Ja
99            Lattrez            Nee             Ja
100         Seefelder            Nee             Ja
101            Grüner            Nee             Ja

## Van Jupyter Notebook naar Pythonproject

1. Richt de map waarin jullie tot nu toe hebben gewerkt in volgens de mappenstructuur uit de slides.
2. Maak van de ontstane mappenstructuur een Pythonproject dat uitvoerbaar is vanuit de terminal. Maak daarin een .py-bestand dat minstens 5 antwoorden uit dit notebook (in de vorm van een DataFrame) exporteert naar Excelbestanden. Alle notebooks mogen als notebook blijven bestaan.
3. Zorg ervoor dat dit Pythonproject zijn eigen repo heeft op Github. Let op: je virtual environment moet <b><u>niet</u></b> meegaan naar Github.

Je mag tijdens dit proces je uit stap 1 ontstane mappenstructuur aanpassen, zolang je bij het beoordelingsmoment kan verantwoorden wat de motivatie hierachter is. De slides verplichten je dus nergens toe.